version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "users"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
  user-api:
    image: user-api:0.0.1-SNAPSHOT
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_URL: jdbc:postgresql://postgres:5432/users
      SERVICE_THREADS: 50
    depends_on:
      - postgres
    ports:
      - "8080:8080"