addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.3.2")
addSbtPlugin("com.typesafe.sbt" % "sbt-native-packager" % "1.7.0")
addSbtPlugin("com.eed3si9n" % "sbt-buildinfo" % "0.9.0")
addSbtPlugin("io.gatling" % "gatling-sbt" % "3.1.0")
addSbtPlugin("com.tapad" % "sbt-docker-compose" % "1.0.35")
